export const baseURL = process.env.NEXT_PUBLIC_BASE_URL;

export const BACKEND_URLS = {
  auth: {
    login: "/auth/login",
    signup: "/auth/signup",
    getUser: "/auth/get-user",
    deleteUser: "/auth/delete-user",
    updateProfile: "/auth/update-profile",
    changePassword: "/auth/change-password",
    initiatePasswordReset: "/auth/initiate-password-reset",
    resetPassword: "/auth/reset-password",
    uploadProflePic: "/auth//upload-profile-pic",
    uploadImage: "/auth/upload-image",
    getProfilePic: "/auth/get-profile-pic",
    findUsersWithoutSubscription: "/auth/find-users-without-subscription",
    signupGoogle: "/auth/signup-google",
    addMjUser: "/auth/add-mj-users",
    addSingleMjUser: "/auth/add-mj-user",
  },
  imageGen: {
    uploadImage: "/image/upload-image",
    generateImage: "/image/generate-image",
    remixIdiogram: "/image/remix-ideogram",
    describeIdiogram: "/image/describe-ideogram",
    saveMjImage: "/image/save-mj-image",
    sendAction: "/image/send-action",
    upscaleImage: "/image/upscale-image",
  },
  subscription: {
    updateSubscription: "/subscription/update-subscription",
    deleteSubscription: "/subscription/delete-subscription",
    getSubscription: "/subscription/get-subscription",
    getSubscriptions: "/subscription/get-subscriptions",
  },
  agent: {
    createAgent: "/agent/create-agent",
    updateAgent: "/agent/update-agent",
    getAgent: "/agent/get-agent",
    getAgentsPerLevel: "/agent/get-agents-per-level",
    getAllAgents: "/agent/get-all-agents",
    deleteAgent: "/agent/delete-agent",
  },
  conversation: {
    createConversation: "/conversation/create-conversation",
    getConversations: "/conversation/get-conversations",
    getConversation: "/conversation/get-conversation",
    deleteConversation: "/conversation/delete-conversation",
    changeConversationName: "/conversation/change-conversation-name",
    startConversation: "/conversation/start-conversation",
    retrieveMessage: "/conversation/retrieve-message",
    checkStatus: "/conversation/check-status",
    newMessage: "/conversation/new-message",
  },
  game: {
    generateSudoku: "/games/generate-sudoku",
    generateCrossword: "/games/generate-crossword",
    generateWordSearch: "/games/generate-wordsearch",
    generateHangman: "/games/generate-hangman",
    generateCryptogram: "/games/generate-cryptogram",
    generateScrambleWord: "/games/scramble-word",
    generateMaze: "/games/generate-maze",
    generateMinesweeper: "/games/generate-minesweeper",
    generateKakuro: "/games/generate-kakuro",
  },
  stripe: {
    startSubscription: "/stripe/start-subscription",
    getStripePortal: "/stripe/get-stripe-portal",
    purchaseCredits: "/stripe/purchase-credits",
  },
  audio: {
    transcribe: "/audio/transcribe",
  }
};
